FROM node:16

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY ./client ./client

RUN npm run build:client

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "client/dist"]
