FROM node:16

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY ./client ./client

RUN npm run build:prd

RUN npm install -g serve

EXPOSE 8080

CMD ["serve", "-s", "client/dist", "-l", "8080"]
