version: '3.8'

services:
  backend:
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development

  frontend:
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development